"""initial_schema

Revision ID: 80e9a7f06daf
Revises: 
Create Date: 2026-05-13 16:39:00.070739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '80e9a7f06daf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    insp = inspect(bind)
    if not insp.has_table("tickets"):
        return
    cols = {c["name"] for c in insp.get_columns("tickets")}
    if "sla_breached" not in cols:
        op.add_column(
            "tickets",
            sa.Column("sla_breached", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        )
    if "reported_by_name" not in cols:
        op.add_column("tickets", sa.Column("reported_by_name", sa.String(length=200), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'reported_by_name')
    op.drop_column('tickets', 'sla_breached')
    # ### end Alembic commands ###
